[package]
name = "file-encrypt-decrypt"
version = "0.1.0"
edition = "2021"

[dependencies]
arboard = "3.4.1"
colored = "2.1.0"
rpassword = "7.3.1"
serde = "1.0.210"
serde-encrypt = "0.7.0"
serde_json = "1.0.128"
sha2 = "0.10.8"
